version: "3.8"
services:
    backend:
        build: .
        ports:
            - "4000:3000"

    database:
        image: mongo:4.0.28-xenial
        ports:
            - "27017:27017"
        volumes:
            - mongodb-data:/data/db

volumes:
    mongodb-data:
